services:
  migrate:
    environment:
      REPORT_LLM_BASE_URL: http://ollama:11434

  api:
    environment:
      REPORT_LLM_BASE_URL: http://ollama:11434

  scheduler:
    environment:
      REPORT_LLM_BASE_URL: http://ollama:11434

  telegram_pipeline:
    environment:
      REPORT_LLM_BASE_URL: http://ollama:11434
      #TG_SESSION_NAME: /app/runtime/tg_analytics.session
      TG_SESSION_NAME: /app/runtime/tg_analytics_new.session

  ai_pipeline:
    environment:
      REPORT_LLM_BASE_URL: http://ollama:11434
