"""init tables

Revision ID: 41fa52103b88
Revises: 
Create Date: 2026-02-10 23:09:51.336729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41fa52103b88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_username'), 'channels', ['username'], unique=True)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('tg_message_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('last_comments_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments_scan_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'tg_message_id', name='uq_posts_channel_msg')
    )
    op.create_index('ix_posts_channel_date', 'posts', ['channel_id', 'date'], unique=False)
    op.create_index(op.f('ix_posts_channel_id'), 'posts', ['channel_id'], unique=False)
    op.create_index(op.f('ix_posts_comments_count'), 'posts', ['comments_count'], unique=False)
    op.create_index(op.f('ix_posts_date'), 'posts', ['date'], unique=False)
    op.create_index(op.f('ix_posts_tg_message_id'), 'posts', ['tg_message_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tg_message_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('author_username', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'tg_message_id', name='uq_comments_channel_msg')
    )
    op.create_index(op.f('ix_comments_channel_id'), 'comments', ['channel_id'], unique=False)
    op.create_index(op.f('ix_comments_date'), 'comments', ['date'], unique=False)
    op.create_index('ix_comments_post_date', 'comments', ['post_id', 'date'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_comments_tg_message_id'), 'comments', ['tg_message_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', name='uq_reports_post')
    )
    op.create_index(op.f('ix_reports_post_id'), 'reports', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_post_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_comments_tg_message_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index('ix_comments_post_date', table_name='comments')
    op.drop_index(op.f('ix_comments_date'), table_name='comments')
    op.drop_index(op.f('ix_comments_channel_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_posts_tg_message_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_date'), table_name='posts')
    op.drop_index(op.f('ix_posts_comments_count'), table_name='posts')
    op.drop_index(op.f('ix_posts_channel_id'), table_name='posts')
    op.drop_index('ix_posts_channel_date', table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_channels_username'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
