from __future__ import annotations

from typing import Any

from services.reporting_v2.state import PipelineState

ALLOWED_PUBLIC_STATUSES = {"ready", "limited", "insufficient_data", "failed"}


def _normalize_public_status(value: str | None) -> str:
    normalized = (value or "").strip().lower()
    if normalized in ALLOWED_PUBLIC_STATUSES:
        return normalized
    return "limited"


def map_state_to_internal_multi_agent_trace(state: PipelineState) -> dict[str, Any]:
    return {
        "version": "v1",
        "status": _normalize_public_status(state.status),
        "context": state.context.model_dump(mode="python"),
        "routing": state.routing.model_dump(mode="python"),
        "retrieval": state.retrieval.model_dump(mode="python"),
        "expert": state.expert.model_dump(mode="python"),
        "public_opinion": state.public_opinion.model_dump(mode="python"),
        "synthesis": state.synthesis.model_dump(mode="python"),
        "reviewer": state.reviewer.model_dump(mode="python"),
        "trace": dict(state.internal_trace),
    }


def map_state_to_public_model_info(state: PipelineState) -> dict[str, Any] | None:
    if state.model_info is None:
        return None
    return state.model_info.model_dump(mode="python")


def map_state_to_public_post_payload(
    *,
    state: PipelineState,
    post_id: int,
    published_at_iso: str,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "type": "post_report_v2",
        "status": _normalize_public_status(state.status),
        "post_id": int(post_id),
        "published_at": published_at_iso,
        "title": f"Post {post_id} discussion snapshot",
        "summary": state.synthesis.summary or "Generated by reporting_v2 mapper skeleton.",
        "comment_count": len(state.comments),
        "confidence": {
            "overall": "low",
            "reason": state.synthesis.confidence_reason or "mapper_skeleton",
        },
        "meta": {
            "multi_agent": map_state_to_internal_multi_agent_trace(state),
        },
    }
    model_info = map_state_to_public_model_info(state)
    if model_info is not None:
        payload["model_info"] = model_info
    return payload
