from __future__ import annotations

from typing import Any

from services.reporting_v2.contracts_internal import validate_multi_agent_meta
from services.reporting_v2.state import PipelineState

ALLOWED_PUBLIC_STATUSES = {"ready", "limited", "insufficient_data", "failed"}


def _normalize_public_status(value: str | None) -> str:
    normalized = (value or "").strip().lower()
    if normalized in ALLOWED_PUBLIC_STATUSES:
        return normalized
    return "limited"


def _default_step_provenance(*, status: str, run_count: int) -> dict[str, Any]:
    normalized_status = status if status in {"completed", "failed", "skipped"} else "completed"
    return {
        "provider": "deterministic",
        "model": "reporting_v2_policy",
        "executed": True,
        "success": normalized_status != "failed",
        "latency_ms": None,
        "input_ref": None,
        "input_hash": None,
        "output_ref": None,
        "output_hash": None,
        "fallback_used": normalized_status == "failed",
        "fallback_reason": "stage_failed" if normalized_status == "failed" else None,
        "attempt_index": max(0, run_count - 1),
        "status": normalized_status,
    }


def map_state_to_internal_multi_agent_trace(state: PipelineState) -> dict[str, Any]:
    stage_state = ((state.internal_trace or {}).get("stages") or {})

    def _step(name: str, payload: dict[str, Any]) -> dict[str, Any]:
        stage = stage_state.get(name) if isinstance(stage_state, dict) else {}
        status = str((stage or {}).get("status") or "completed")
        run_count = int((stage or {}).get("run_count") or 1)
        step = {
            "status": status,
            "run_count": run_count,
            "provenance": _default_step_provenance(status=status, run_count=run_count),
        }
        step.update(payload)
        return step

    multi_agent = {
        "version": "v1",
        "status": _normalize_public_status(state.status),
        "epistemic_claims": list(state.expert.claims),
        "steps": {
            "context": _step("context", state.context.model_dump(mode="python")),
            "routing": _step("routing", state.routing.model_dump(mode="python")),
            "expert": _step("expert", state.expert.model_dump(mode="python")),
            "public_opinion": _step("public_opinion", state.public_opinion.model_dump(mode="python")),
            "synthesis": _step("synthesis", state.synthesis.model_dump(mode="python")),
            "reviewer": _step("reviewer", state.reviewer.model_dump(mode="python")),
        },
        "retrieval": state.retrieval.model_dump(mode="python"),
        "review": {
            "iterations": int(state.reviewer.iterations),
            "history": list(state.reviewer.history),
        },
    }
    return validate_multi_agent_meta(multi_agent).model_dump(mode="python")


def map_state_to_public_model_info(state: PipelineState) -> dict[str, Any] | None:
    if state.model_info is None:
        return None
    return state.model_info.model_dump(mode="python")


def map_state_to_public_post_payload(
    *,
    state: PipelineState,
    post_id: int,
    published_at_iso: str,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "type": "post_report_v2",
        "status": _normalize_public_status(state.status),
        "post_id": int(post_id),
        "published_at": published_at_iso,
        "title": f"Post {post_id} discussion snapshot",
        "summary": state.synthesis.report_text or state.synthesis.summary or "Generated by reporting_v2 mapper skeleton.",
        "comment_count": len(state.comments),
        "confidence": {
            "overall": "low",
            "reason": state.synthesis.confidence_reason or "mapper_skeleton",
        },
        "meta": {
            "multi_agent": map_state_to_internal_multi_agent_trace(state),
        },
    }
    model_info = map_state_to_public_model_info(state)
    if model_info is not None:
        payload["model_info"] = model_info
    return payload
