use_default_settings: true

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "change-this-secret-key"
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "ru"
  formats:
    - html
    - json

ui:
  static_use_hash: true

outgoing:
  request_timeout: 8.0

botdetection:
  ip_limit:
    filter_link_local: false
    link_token: false
  ip_lists:
    pass_ip:
      - 127.0.0.1
      - ::1